apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vtclfepg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vtclfepg:dfa7cffe87a6e02c7aca34ab966231410b6c4881@sha256:cd354db231ffa492468129b922ee5664216611271e3d4d4e9f479dcab8e93eee
          name: container-image
